# -*- coding: utf-8 -*-
"""DataVizProjectCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wp-f13DoGsIearQ0CQFy-mxR7FNbggs
"""

import streamlit as st
import numpy as np

# Using object notation
add_selectbox = st.sidebar.selectbox(
    "Controls",
    ("Email", "Home phone", "Mobile phone")
)

# Using "with" notation
with st.sidebar:
    add_radio = st.radio(
        "Controls",
        ("Standard (5-15 days)", "Express (2-5 days)")
    )

# Columns with individual controls
col1, col2, col3 = st.columns(3)


with col1:
   st.header("A cat")
   st.image("https://static.streamlit.io/examples/cat.jpg")

with col2:
   st.header("A dog")
   st.image("https://static.streamlit.io/examples/dog.jpg")

with col3:
   st.header("An owl")
   st.image("https://static.streamlit.io/examples/owl.jpg")

# Container with graph
with st.container():
   st.write("This is inside the container")

   # You can call any Streamlit command, including custom components:
   st.bar_chart(np.random.randn(50, 3))

st.write("This is outside the container")

# Second chart
# Columns for chart/controls
cols1, cols2 = st.columns(2)


with cols1:
   st.header("A cat")
   st.image("https://static.streamlit.io/examples/cat.jpg")

with cols2:
   st.header("A dog")
   st.image("https://static.streamlit.io/examples/dog.jpg")